name: Auto PR Comment

on:
  pull_request:
    types: [opened]
    paths:
      - 'index.ts'
      - 'Pulumi.yaml'
      - 'Pulumi.*.yaml'

jobs:
  comment:
    if: github.actor != 'claude-code[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@claude update the diagrams to reflect any infrastructure changes.'
            })