C4Context
    title System Context diagram for Simple Web Application

    Person(web_user, "Web User", "End user with HTTP access from allowed IP range")
    Person(admin_user, "Admin User", "System administrator with SSH access from allowed IP range")
    
    System_Boundary(aws, "AWS Cloud") {
        System(webserver, "Web Server", "EC2 t2.micro instance with Python SimpleHTTPServer<br/>Serves static HTML content on port 80<br/>Access restricted to specific IP range")
    }
    
    System_Ext(internet, "Internet", "Public internet infrastructure")
    System_Ext(restricted_access, "Access Control", "Security group restricts access to allowed IP ranges")
    
    Rel(web_user, webserver, "Accesses web content", "HTTP/80 from allowed IP range")
    Rel_Back(webserver, web_user, "Returns HTML content", "HTTP Response")
    Rel(admin_user, webserver, "SSH administration", "SSH/22 from allowed IP range")
    Rel_Back(webserver, admin_user, "Command responses", "SSH Response")
    BiRel(webserver, internet, "Limited internet connectivity", "TCP/IP via security group")
    Rel(restricted_access, webserver, "Enforces IP restrictions", "Security policies")

    UpdateRelStyle(web_user, webserver, $textColor="blue", $lineColor="blue")
    UpdateRelStyle(webserver, web_user, $textColor="green", $lineColor="green")
    UpdateRelStyle(admin_user, webserver, $textColor="purple", $lineColor="purple")
    UpdateRelStyle(webserver, admin_user, $textColor="orange", $lineColor="orange")
    UpdateRelStyle(webserver, internet, $textColor="orange", $lineColor="orange")
    UpdateRelStyle(restricted_access, webserver, $textColor="red", $lineColor="red")

    UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")